### ISSUE TITLE
[FEATURE REQUEST] Add dockerfile integration for development/test

### ISSUE THREAD

**Issue by litan1106** [spiral/roadrunner-binary#61]
**Is your feature request related to a problem? Please describe.**
Easier to get started with dockerfile integration. Ex: skip all the local go sdk and php installation.

**Describe the solution you'd like**
Add a dockerfile integration for development/test so we can skip the local go sdk and php installation.

**Additional context**

for example:
- setup a dockerfile with golang:1.16-buster as base
- add php to the dockerfile
- setup Goland to run remote target via docker (or debug in vscode with docker)
- debug/test in Goland (or debug/test in vscode)

**Comment by tarampampam** [comment]
@litan1106 Did you mistakes with the repository? :)

Did I think we [talk about](https://github.com/spiral/roadrunner/pull/575#issuecomment-843280744) https://github.com/spiral/roadrunner, or not?

**Comment by 48d90782** [comment]
@litan1106 Actually, you don't need to have a separate dockerfile. To modify and test your RR plugins or modifications locally, please, follow the next steps:
1. Clone RR and RR-binary repositories.
2. Do a RR `replace` in the RR-Binary `go.mod`. Example: 
```go
replace (
	github.com/spiral/roadrunner/v2 => ../roadrunner
)
```
3. Build the binary with the current Dockerfile from this repository.

**Comment by litan1106** [comment]
> @litan1106 Actually, you don't need to have a separate dockerfile. To modify and test your RR plugins or modifications locally, please, follow the next steps:
> 
> 1. Clone RR and RR-binary repositories.
> 2. Do a RR `replace` in the RR-Binary `go.mod`. Example:
> 
> ```go
> replace (
> 	github.com/spiral/roadrunner/v2 => ../roadrunner
> )
> ```
> 
> 1. Build the binary with the current Dockerfile from this repository.

The dockerfile from the roadrunner-binary only for build the cli but not for running the tests. (aka: php tests)

**Comment by 48d90782** [comment]
I'm not sure, what `php test` do you mean, but RR-core does not contain PHP (only for the internal testing) as well as the RR-binary.

**Comment by 48d90782** [comment]
Dockerfile from the RR-binary builds the whole RR with all plugins, not only CLI.

**Comment by litan1106** [comment]
> Dockerfile from the RR-binary builds the whole RR with all plugins, not only CLI.
yes, it builds everything but the dockerfile doesn't contain the php binary for local development and testing.

**Comment by 48d90782** [comment]
@litan1106 friendly ping :) Is this fit your needs if I add `Dockerfile.dev` file to the repo with PHP installed inside?

**Comment by zolotov88** [comment]
I'm tring to develop with Laravel Octane and custom rr binary.

**Comment by zolotov88** [comment]
I'm tring to develop with Laravel Octane and custom RR binary.
1. I have no docs how I need to compile RR binary. It is outdated.
2. I have not any simple how I can make "go run" with my app. I want make custom middlewares. Need I build on every change? I started `CGO_ENABLED=0 go run -trimpath -ldflags "-s" /rr/cmd/rr serve -c /var/www/.rr.yaml -d`. Works, but do not applies changes in go files (plugins). Why?
3. Why version is undefind if I do not provide a params on build? Octane do not work with undefind version. Additional params on build are the third wheel.
4. Why RR do not working without building with CGO_ENABLED=0?
5. What mean '-ldflags "-s"'? Why I need that?
6. Why I need '-trimpath' on every build?
7. If I do not need your Dockerfile need I do `CGO_ENABLED=0 go build -trimpath -ldflags "-s \
-X github.com/spiral/roadrunner-binary/v2/internal/meta.version=v2.2.1" -o ./rr ./cmd/rr` in console instead `go build -o ./rr ./cmd/rr` every time?

**Comment by 48d90782** [comment]
1. Yeah, docs are outdated, but I'll update it in the 2.3.0 
2. Sure, you need to compile binary on every change 😃 It's hard to say, why your changes are not applied. Provide the steps you are executing, and I'll try to help you.
3. Version injected into the binary at the linking state. By default, it's undefined (because there is no version till you specify it). If you want to inject the version, you have 2 options: 1. Manually change the version https://github.com/spiral/roadrunner-binary/blob/master/internal/meta/meta.go#L7 2. Specify LDFLAGS during the build - https://github.com/spiral/roadrunner-binary/blob/master/.github/workflows/release.yml#L64
4. GO produces statically linked binaries. With disabled CGO, GO doesn't use system dependencies at all (like Glibc, for example, for the user or system packages). But actually, RR does work with CGO enabled. You need to have a compatible system if you move go's binary. Also, keep in mind that Alpine Linux does not use GCC in the flavor of musl-gcc, which is incompatible with GCC.
5. It means to remove debug info and symtable at the linking stage: https://golang.org/cmd/link/.
6. You don't. But in case of panic, your binary will include your LOCAL paths, like `/home/valery/roadrunner/....` This is sensitive information that you should remove from the build. But if you want that users would see your local path on the external server, it's on your own )
7. To omit using -X linker flag, you may refer to the p3.1 above

Thank you very much. I'll try to update as many docs as I can due to the 2.3.0 release. Also, feel free to join our discord server and ask any questions here, and I'll help you in real-time.

**Comment by zolotov88** [comment]
@48d90782 Thanks for the very detailed answer!

**Comment by litan1106** [comment]
@rustatian I think this Dockerfile.dev could be remove in favor of the better local development PR.
