### ISSUE TITLE
[EXT INTEGRATIONS] Laravel Octane with roadrunner unresponsive after benchmark

### ISSUE THREAD

**Issue by dyanakiev** [spiral/roadrunner-binary#62]
- Octane Version: latest
- Laravel Version: latest
- PHP Version: 8.0.6
- RoadRunner version: rr version 2.2.1 (build time: 2021-05-13T18:00:30+0000, go1.16.4)
- Database Driver & Version: n/a
- Workers: 16 
- OS: MacOS Big Sur

### Description:
Hello, i installed octane on plain laravel setup then i ran `wrk -t12 -c400 -d30s http://localhost:8000/` to test, after it finished the octane/roadruner server become unresponsive and this error thrown in the browser 

```
http_plugin_serve_http: Timeout:
    supervised_exec_with_context: context deadline exceeded
```

There are also more than 20 of this processes
![image](https://user-images.githubusercontent.com/11967079/119231828-65276300-bb2b-11eb-9a9f-03868af35d67.png)

Is this normal behaviour? I hit it really hard but i would expect it to resurrect itself but it's still unresponsive even after few minutes. In another test Swoole handled the requests fine.

### Steps To Reproduce:
1. install laravel
2. install octane with roadrunner
3. run `wrk -t12 -c400 -d30s http://localhost:8000/`

**Comment by wolfy-j** [comment]
Hmmm, do you have any idea what is causing workers to reset? Is it part of your benchmark? Resetting will obviously load RR too much to behave well under benchmark.

**Comment by 48d90782** [comment]
Hello @dyanakiev. That's totally not normal behavior. I mean, a bunch of the `./rr reset`. I don't know why `octane` decided to `reset` the workers during the load test. `./rr reset` operation is blocking operation because when you bombard the RR with `wrk`, `reset` operation wait on the mutex. Octane, in turn, for some reason, allocated a lot of the `./rr reset` processes (reset backoff ??).

Regarding the allocate timeout error: It's normal because when you bombard RR, it holds a request until the worker is freed. But if the worker is busy with the actual work it can't get the next request in a queue. So, you need to increase allocate timeout or number of workers.

**Comment by 48d90782** [comment]
@dyanakiev Hey. Since this is an external integration issue, it would be better to ask Octane maintainers about `reset` backoff. Feel free to re-open this issue if you would need help from our side.
